return {}
-- local config = function()
-- 	local theme = require("lualine.themes.carbonfox")
-- 	theme.normal.c.bg = nil
--
-- 	require("lualine").setup({
-- 		options = {
-- 			theme = theme,
-- 			globalstatus = true,
-- 			component_separators = { left = "|", right = "|" },
-- 			section_separators = { left = "", right = "" },
-- 		},
-- 		sections= {
-- 			lualine_a = { "mode", "branch" },
-- 			lualine_b = { "buffers" },
-- 			lualine_x = { "encoding", "fileformat", "filetype" },
-- 			lualine_y = { "progress" },
-- 			lualine_z = { "location" },
-- 		},
-- 		tabline = {},
-- 	})
-- end
--
-- return {
-- 	"nvim-lualine/lualine.nvim",
-- 	lazy = false,
-- 	config = config,
-- }
